# Generated by Django 5.2.6 on 2025-11-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_workfromhome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
