# Generated by Django 5.2.7 on 2025-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
