# Generated by Django 5.2.6 on 2025-11-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
