# Generated by Django 5.2.6 on 2025-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
